### ISSUE TITLE
Push to incorrect dir on successive try

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/tbtbtc#22]
As a user that made a mistake and pushed a PR to the wrong dir, when I try to push again to the proper dir, the successive PR pushes to the original mistaken dir.

<img width="700" alt="Screen Shot 2023-01-06 at 11 38 12 AM" src="https://user-images.githubusercontent.com/755825/211056646-848a689b-a416-4d0a-934a-c26c613c4d6e.png">

<img width="691" alt="Screen Shot 2023-01-06 at 11 39 47 AM" src="https://user-images.githubusercontent.com/755825/211056829-23229b10-bcb9-4799-a2a8-7b8ab521556e.png">

**Comment by tvpeter** [comment]
I'm unable to reproduce this error, pls can you recheck with the updates?

**Comment by adamjonas** [comment]
I'll try to reproduce. For now, let's focus on the other issues.

**Comment by adamjonas** [comment]
I haven't seen this for a few PRs now so closing.
