### ISSUE TITLE
update auto transcript_by

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/tbtbtc#44]
Update to `transcript_by: youtube_to_bitcoin_transcript_v_1.0.0` to `transcriber_to_bitcoin_transcript_0.1`

**Comment by masterchief164** [comment]
does this work?
`transcript_by: transcriber_to_bitcoin_transcript_v_{1.0.0}`

**Comment by adamjonas** [comment]
I was thinking of including the name or at least the github name as well.

How about `Shaswat Gupta via TBTBTC v1.0.0` or `masterchief164 via TBTBTC v1.0.0`
