### ISSUE TITLE
update commit messages to be more descriptive

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/tbtbtc#46]
`initial transcription using tstbtc tool` is non-descript and is going to be a frequently seen commit in bitcoin transcripts. Add the title of the file being transcribed as well as top level dir to help better describe the commit

**Comment by masterchief164** [comment]
does something like this work? `added PCs don’t stand a chance… in sob1 by masterchief164` where `added PCs don’t stand a chance…` is the file name, `sob1/2021` was the loc provided and `masterchief164` was the username

**Comment by masterchief164** [comment]
https://github.com/masterchief164/bitcointranscripts/pull/23 is the sample PR

**Comment by adamjonas** [comment]
The title should sufffice. You can gather the rest of the context from the PR.
