### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/tbtbtc#5]
Some optional arguments might include:

- [x] what directory to place in the btc transcripts project
- [x] the file name (to override the date fetched from youtube)
- [x] Date of recording (to override the date fetched from youtube)
- [x] Tags
- [x] Category
- [x] Speaker names & number of speakers
- [x] size of the whisper model

**Comment by tvpeter** [comment]
First and last are done.

**Comment by adamjonas** [comment]
Rest were closed via #32
